apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: copenhagen-tranegilde-infra
  namespace: flux-workspace
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: source-repository
    namespace: default
  path: ./clusters/copenhagen-tranegilde/infra
  prune: true
  decryption:
    provider: sops
